#!/usr/bin/env bash

# make.sh
#
# Copyright (C) 2026 Kristofer Berggren
# All rights reserved.
#
# See LICENSE for redistribution information.

# exiterr
exiterr()
{
  >&2 echo "${1}"
  exit 1
}

# show_usage
show_usage()
{
  echo "usage: make.sh [OPTIONS] ACTION"
  echo ""
  echo "Options:"
  echo "  --yes,-y  - non-interactive mode, assume yes"
  echo ""
  echo "Action:"
  echo "  deps      - install project dependencies"
  echo "  build     - perform build"
  echo "  doc       - perform build and generate documentation"
  echo "  install   - perform build and install"
  echo "  uninstall - perform build and uninstall"
  echo "  all       - perform all actions except uninstall"
}

# process arguments
DEPS="0"
BUILD="0"
DOC="0"
INSTALL="0"
UNINSTALL="0"
YES=""

if [[ "${#}" == "0" ]]; then
  show_usage
  exit 1
fi

while [[ ${#} -gt 0 ]]; do
  case "${1%/}" in
    deps)
      DEPS="1"
      ;;

    build)
      BUILD="1"
      ;;

    doc)
      BUILD="1"
      DOC="1"
      ;;

    install)
      BUILD="1"
      INSTALL="1"
      ;;

    uninstall)
      BUILD="1"
      UNINSTALL="1"
      ;;

    all)
      DEPS="1"
      BUILD="1"
      TESTS="1"
      DOC="1"
      INSTALL="1"
      ;;

    -y|--yes)
      YES="-y"
      ;;

    *)
      show_usage
      exit 1
      ;;
  esac
  shift
done

# deps
if [[ "${DEPS}" == "1" ]]; then
  OS="$(uname)"
  if [ "${OS}" == "Linux" ]; then
    unset NAME
    eval $(grep "^NAME=" /etc/os-release 2> /dev/null)
    if [[ "${NAME}" == "Ubuntu" ]]; then
      sudo apt update && sudo apt ${YES} install cmake || exiterr "deps failed (${NAME}), exiting."
    elif [[ "${NAME}" == "Rocky Linux" ]]; then
      sudo dnf ${YES} install cmake || exiterr "deps failed (${NAME}), exiting."
    else
      exiterr "deps failed (unsupported linux distro ${NAME}), exiting."
    fi
  elif [ "${OS}" == "Darwin" ]; then
    brew install cmake coreutils || exiterr "deps failed (mac), exiting."
  else
    exiterr "deps failed (unsupported os ${OS}), exiting."
  fi
fi

# build
if [[ "${BUILD}" == "1" ]]; then
  OS="$(uname)"
  MAKEARGS=""
  if [ "${OS}" == "Linux" ]; then
    MAKEARGS="-j$(nproc)"
  elif [ "${OS}" == "Darwin" ]; then
    MAKEARGS="-j$(sysctl -n hw.ncpu)"
  fi
  mkdir -p build && cd build && cmake .. && make ${MAKEARGS} && cd .. || exiterr "build failed, exiting."
fi

# doc
if [[ "${DOC}" == "1" ]]; then
  mkman()
  {
    if [[ -x "$(command -v help2man)" ]]; then
      if [[ "$(uname)" == "Darwin" ]]; then
        SED="gsed -i"
      else
        SED="sed -i"
      fi

      help2man -n "${2}" -N -o "./doc/${1}.1" "./bin/${1}" && ${SED} "s/\.\\\\\" DO NOT MODIFY THIS FILE\!  It was generated by help2man.*/\.\\\\\" DO NOT MODIFY THIS FILE\!  It was generated by help2man./g" "./doc/${1}.1" || exiterr "${1} doc failed, exiting."
    fi
  }
  # utils with man-pages
  #mkman "cvc" "common version control"
fi

# install_help
install_help()
{
  MAKETARGET="${1}"
  OS="$(uname)"
  if [ "${OS}" == "Linux" ]; then
    cd build && sudo make ${MAKETARGET} && cd .. || exiterr "${MAKETARGET} failed (linux), exiting."
  elif [ "${OS}" == "Darwin" ]; then
    GHSUDO=""
    if [[ "${GITHUB_ACTIONS}" == "true" ]]; then
      GHSUDO="sudo"
    fi
    cd build && ${GHSUDO} make ${MAKETARGET} && cd .. || exiterr "${MAKETARGET} failed (mac), exiting."
  else
    exiterr "${MAKETARGET} failed (unsupported os ${OS}), exiting."
  fi
}

# install
if [[ "${INSTALL}" == "1" ]]; then
  install_help install
fi

# uninstall
if [[ "${UNINSTALL}" == "1" ]]; then
  install_help uninstall
fi

# exit
exit 0
